import type { QuotationInput } from './QuotationInput.js';
import type { QuotationResult } from './QuotationGenerator.js';

export interface ReportResult {
  reportMarkdown: string;
  exportData: object;
}

export function generateReport(input: QuotationInput, quotation: QuotationResult): ReportResult {
  const boqRows = quotation.boq
    .map((item) => `${item.itemNo}. ${item.description} | ${item.unit} | ${item.quantity} | ${item.directRate} | ${item.directAmount}`)
    .join('\n');
  const calculation = quotation.calculation
    ? `${quotation.calculation.sectionName}: ${quotation.calculation.lengthM}m × ${quotation.calculation.weightKgPerM}kg/m = ${quotation.calculation.totalWeightKg}kg`
    : 'No simple calculation provided.';
  const reportMarkdown = `# VALOR STRUCT\n# QUOTATION REPORT\n\nProject: ${input.projectName}\nClient: ${input.clientName}\nLocation: ${input.location}\nScope: ${input.scopeDescription}\n\n## BOQ TABLE\n${boqRows}\n\n## Commercial Summary\nSubtotal: ${quotation.summary.currency} ${quotation.summary.subtotal}\nOverhead: ${quotation.summary.currency} ${quotation.summary.overhead}\nProfit: ${quotation.summary.currency} ${quotation.summary.profit}\nVAT: ${quotation.summary.currency} ${quotation.summary.vat}\nGrand Total: ${quotation.summary.currency} ${quotation.summary.grandTotal}\n\n## Simple Calculation\n${calculation}\n\n## Terms and Conditions\n${quotation.terms.map((term) => `- ${term}`).join('\n')}\n\nGenerated By:\nAgenticFlow / Valor Struct`;

  return {
    reportMarkdown,
    exportData: { input, quotation },
  };
}
