from __future__ import annotations

from typing import Any, Protocol


class GovernanceStore(Protocol):
    """Lightweight persistence interface shared by demo SQLite and future PostgreSQL stores."""

    def create_project(self, project: dict[str, Any]) -> dict[str, Any]: ...
    def list_projects(self) -> list[dict[str, Any]]: ...
    def create_package_run(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def get_package_run(self, package_run_id: str) -> dict[str, Any]: ...
    def list_package_runs(self) -> list[dict[str, Any]]: ...
    def record_approval_decision(self, package_run_id: str, decision: dict[str, Any]) -> dict[str, Any]: ...
    def create_audit_event(self, package_run_id: str, event: dict[str, Any]) -> dict[str, Any]: ...
    def list_audit_events(self, package_run_id: str) -> list[dict[str, Any]]: ...
    def create_export(self, package_run_id: str, export: dict[str, Any]) -> dict[str, Any]: ...
    def list_exports(self, package_run_id: str) -> list[dict[str, Any]]: ...
