import type { SteelDesignInput } from './SteelDesignInput.js';
import type { SteelDesignContext, UtilizationSummaryResult } from './types.js';

export function generateSteelDesignReport(input: SteelDesignInput, context: SteelDesignContext, summary: UtilizationSummaryResult): string {
  const checks = summary.checks
    .map((check) => `| ${check.checkName} | ${check.demand} | ${check.capacity} | ${check.utilization} | ${check.status.toUpperCase()} |`)
    .join('\n');
  const warnings = context.warnings.length ? context.warnings.map((warning) => `- ${warning}`).join('\n') : '- No missing critical input detected.';
  return `# STEEL DESIGN PACK MVP\n\nPRELIMINARY ENGINEERING CHECK — not a final code-compliant design.\n\nProject: ${input.projectName}\nMember: ${input.memberId}\nCode/Profile: ${input.codeProfile}\nMaterial: ${input.materialGrade}\nSection: ${input.sectionName}\n\n## Utilization Table\n| Check | Demand | Capacity | Utilization | Status |\n| --- | ---: | ---: | ---: | --- |\n${checks}\n\nGoverning check: ${summary.governingCheck}\nGoverning utilization: ${summary.governingUtilization}\nPass/fail status: ${summary.status.toUpperCase()}\n\n## Warnings\n${warnings}\n\nGenerated By: AgenticFlow / Valor Struct`;
}
